'Variable data types
'TYPE_ANY means we have not placed any restrictions on the type of this
'variable yet.
CONST TYPE_ANY = 1
CONST TYPE_BYTE = 2
CONST TYPE_INTEGER = 3
CONST TYPE_LONG = 4
CONST TYPE_INTEGER64 = 5
CONST TYPE_UBYTE = 6
CONST TYPE_UINTEGER = 7
CONST TYPE_ULONG = 8
CONST TYPE_UINTEGER64 = 9
CONST TYPE_SINGLE = 10
CONST TYPE_DOUBLE = 11
CONST TYPE_FLOAT = 12
CONST TYPE_STRING = 13
