name: Release
on:
  push:
    branches:
      - ci
    #tags:
    #  - 'release/*'

jobs:
  mingw-w64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: make
      - name: Install Dependencies
        run: .ci/windows/dependencies.sh
      - name: Build
        run: ./ci/windows/build.sh

