name: Release
on:
  push:
    branches:
      - ci
    tags:
      - 'v*.*.*'

jobs:
  windows10-mingw-x86_64:
    name: Windows 10, MinGW x86_64
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: make p7zip unzip
      - name: Build
        run: .ci/windows/build.sh
      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: .ci/windows/package.sh
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release/lbasic-*
          fail_on_unmatched_files: true

